// <auto-generated />
namespace EasyHosts.Terminal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddColumnHashPicture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColumnHashPicture));
        
        string IMigrationMetadata.Id
        {
            get { return "202211012011581_AddColumnHashPicture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
